modLoader="javafml"
loaderVersion="[40,)"
license="CC-BY-4.0"
issueTrackerURL="https://github.com/malcolmriley/minecraft-textiles/issues"

[[mods]]
modId="paragon_textiles"
version="${file.jarVersion}"
displayName="Wily Textiles"
logoFile="logo.png"
credits="The_Paragon"
authors="Malcolm Riley"
description='''
Are you tired of long nights spent mugging Spiders for their String? This mod can help!

This mod centers around the acquisition of textile products from alternative sources.
'''

[[dependencies.paragon_textiles]]
    modId="forge"
    mandatory=true
    versionRange="[40.1,)"
    ordering="NONE"
    side="BOTH"
